image_width: 640
image_height: 352
num_classes: 21
out_fig_width: 9
out_fig_height: 3
frames_loc: processed_frames
video_loc: video
out_gif_name: segmented_movie.gif 
out_video_name: demo_video.mp4
seg_video_name: segmented_video.mp4
model_loc: models
unet_model_name: UNET.h5
unet_model_doi: 8237790
mean: [0.485, 0.456, 0.406]
std:  [0.229, 0.224, 0.225]
