image_width: 512
image_height: 512
num_classes: 20
out_fig_width: 6
out_fig_height: 3
frames_loc: processed_frames
video_loc: video
out_gif_name: segmented_movie.gif 
out_video_name: demo_video.mp4
seg_video_name: segmented_video.mp4
model_loc: static
unet_model_name: best_model.keras
unet_model_dir: static
mean: [0.485, 0.456, 0.406]
std:  [0.229, 0.224, 0.225]
